name: auto deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:  self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: auto update
        run: |
          cd /home/lighthouse/actions-runner/_work/docsify/docsify
          sh auto_update_docsify.sh
        
