name: auto deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:  self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: auto update
        uses: appleboy/ssh-action@master
        with:
          # 这里配置对应仓库设置的变量，就可以避免服务器配置暴露
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/lighthouse/actions-runner/_work/docsify/docsify
            sh auto_update_docsify.sh
        
